---
title: Small RNA-seq
date:
author: Thomas R Burkard
output:
  html_document:
    theme: united
    highlight: haddock
    code_folding: hide
    toc: true
    number_sections: true
    toc_depth: 3
    toc_float: true
---

# Merge read and UMI count files

```{r mergeCnt}
cnt.files <- list.files(path = "count", pattern = "*.count.txt", full.names = TRUE)
cnt.files

tables <- lapply(cnt.files, function(f) {
    tmp <- read.delim(f)
    rownames(tmp) <- tmp$Name
    id <- rownames(tmp)
    id2 <- rownames(tmp)
    id2 <- gsub("-5p$", "-Threep", id2)
    id2 <- gsub("-3p$", "-5p", id2)
    id2 <- gsub("-Threep", "-3p", id2)
    tmp <- cbind(tmp, miR=tmp[id, "Total"] > tmp[id2, "Total"] | is.na(tmp[id, "Total"] > tmp[id2, "Total"]))
    name <- sub("count/(.*).trimmed.clean.seqCnt.count.txt", "\\1", f)
    colnames(tmp) <- c("Name", paste0(c("GM", "PM", "Total", "GM.UMInum", "PM.UMInum", "Total.UMInum", "GM.UMIfr", "PM.UMIfr", "Total.UMIfr", "miR"), ".", name))
    return(tmp)
})

cnt.table <- Reduce(function(dtf1, dtf2) merge(dtf1, dtf2, by = "Name", all = TRUE), tables)

write.table(cnt.table, file = "countTable.txt", sep = "\t", quote = F, row.names = F)

```

# Merge spike-in read and UMI count files
```{r mergeSpikeIn}
spike.files <- list.files(path = "spikeIn", pattern = "*.spikeIn.txt", full.names = TRUE)
spike.files

spike.tables <- lapply(spike.files, function(f) {
  tmp <- read.delim(f, header = TRUE)
  tmp = t(tmp)
  id <- rownames(tmp)[1:8]
  tmp1 = tmp[c(1:8), ]
  tmp2 = tmp[c(9:16), ]
  names(tmp1) = id
  names(tmp2) = id
  #tmp = cbind(id, t(tmp[1, c(1:8)]), t(tmp[1, -c(1:8)))
  tmp = data.frame(id, tmp1, tmp2, stringsAsFactors = FALSE)

  name <- sub("count/(.*).trimmed.clean.seqCnt.count.txt", "\\1", f)
  colnames(tmp) <- c("Name", paste0(c("Total", "Total.UMI"), ".", name))
  return(tmp)
})

spike <- Reduce(function(dtf1, dtf2) merge(dtf1, dtf2, by = "Name", all = TRUE), spike.tables)
write.table(spike, file = "spikeInTable.txt", sep = "\t", quote = F, row.names = F)
spike

```

# Merge count statistics
```{r mergeCntStat}

cntStat1.files <- list.files(path = "countStat_part1", pattern = "*.countStat.txt", full.names = TRUE)
cntStat1.tables <- lapply(cntStat1.files, read.delim)
cntStat1 <- Reduce('rbind', cntStat1.tables)

# write.table(cntStat1, file = "countStatTable.txt", sep = "\t", quote = F, row.names = F)
#cntStat1

cntStat2.files <- list.files(path = "countStat_part2", pattern = "*.countStat.txt", full.names = TRUE)
cntStat2.tables <- lapply(cntStat2.files, read.delim)
cntStat2 <- Reduce('rbind', cntStat2.tables)

#cntStat2

#stat1 = cntStat1
#stat2 = cntStat2
stat1 = data.frame(cntStat1, stringsAsFactors = FALSE)
stat2 = data.frame(cntStat2, stringsAsFactors = FALSE)

stat1
stat2

index1 = c()
index2 = c()
for(n in 1:nrow(stat1))
{
  kk = grep(as.character(stat1[n, 1]), as.character(stat2[, 1]))
  index1 = c(index1, rep(n, length(kk)))
  index2 = c(index2, kk)
}

stat.all = data.frame(stat1[index1, ], stat2[index2, ], stringsAsFactors = FALSE)
#colnames(stat.all) = c(colnames(stat1), colnames(stat2))

write.table(stat.all, file = "countStatTable.txt", sep = "\t", quote = F, row.names = F)

stat.all

```


# Session info
```{r sessionInfo}
sessionInfo()
```
